//! Utility functions and types for serializing and deserializing messages according to
//! the [Wayland wire format](https://wayland.freedesktop.org/docs/html/ch04.html).

const std = @import("std");
const builtin = @import("builtin");

const Fixed = @import("fixed.zig").Fixed;

const log = std.log.scoped(.wayland_wire);

pub const libwayland_max_message_size = 4096;
pub const libwayland_max_message_args = 20;
pub const client_min_id = 0x00000002;
pub const client_max_id = 0xfeffffff;
pub const server_min_id = 0xff000000;
pub const server_max_id = 0xfffffffe;

/// Two-word message header containing target object id, message opcode, and length in bytes,
/// including the header.
pub const Header = switch (builtin.target.cpu.arch.endian()) {
    .little => extern struct {
        object: u32,
        opcode: u16,
        length: u16,
    },
    .big => extern struct {
        object: u32,
        length: u16,
        opcode: u16,
    },
};

/// When the type of a `new_id` argument cannot be inferred from the xml, it must be prefixed
/// with the interface, a string, and the version, a u32.
pub const GenericNewId = struct {
    interface: [:0]const u8,
    version: u32,
    new_id: u32,

    /// Initialize a generic new id from the parameters that will be present in codegen.
    pub fn init(comptime T: type, version: T.Version, new_id: u32) GenericNewId {
        return .{
            .interface = T.interface,
            .version = @intFromEnum(version),
            .new_id = new_id,
        };
    }
};

pub const SerializeError = error{MessageTooLong};

/// Serialize `args` to `buffer`, encoding `object` and `opcode` in the header.
/// Expects that no fds are passed in args, as fds are sent over ancillary.
/// Returns the length of the serialized message, including the header.
/// Returns `error.MessageTooLong` if the length of the message would exceed the libwayland-imposed
/// maximum message size of 4096 or overflow `buf`.
pub fn serializeMessage(
    buf: []u8,
    object: u32,
    comptime opcode: u16,
    args: anytype,
) SerializeError!usize {
    comptime if (std.meta.fields(@TypeOf(args)).len > libwayland_max_message_args)
        @compileError("Too many args.");

    const length = calculateArgsLength(args);
    if (length > libwayland_max_message_size)
        return error.MessageTooLong;

    std.mem.bytesAsValue(Header, buf[0..@sizeOf(Header)]).* = .{
        .object = object,
        .opcode = opcode,
        .length = length,
    };

    var index: usize = @sizeOf(Header);
    inline for (@typeInfo(@TypeOf(args)).@"struct".fields) |f| {
        if (index >= buf.len) return error.MessageTooLong;
        index += serializeArg(buf[index..], @field(args, f.name));
    }
    std.debug.assert(index == length);

    return length;
}

pub const DeserializeError = error{InvalidArguments};

/// Constructs a `T`  from `bytes` and `fds`. Expects `T` to have been generated by the scanner.
/// Returns `T` on success.
/// Returns `error.InvalidArguments` if `bytes` or `fds` is found to contain invalid data
/// for constructing `T`, or are too small.
pub fn deserializeMessage(
    comptime T: type,
    bytes: []const u8,
    fds: []const std.posix.fd_t,
) DeserializeError!T {
    const signature = T._signature;
    var message: T = undefined;
    var index: usize = 0;
    var fd_index: usize = 0;

    inline for (@typeInfo(T).@"struct".fields[1..], signature) |field, sig_byte| {
        if (sig_byte == 'd') { // field is an fd
            if (fd_index == fds.len) return error.InvalidArguments;
            @field(message, field.name) = fds[fd_index];
            fd_index += 1;
            continue;
        }

        if (index >= bytes.len) return error.InvalidArguments;
        const val, const size = try deserializeField(field.type, bytes[index..]);
        @field(message, field.name) = val;
        index += size;
    }

    return message;
}

/// Serialize a single argument, `arg`, to `buffer`.
/// Returns the length of `arg` as serialized.
fn serializeArg(buffer: []u8, arg: anytype) usize {
    const T = @TypeOf(arg);
    return switch (@typeInfo(T)) {
        .int => switch (T) {
            i32 => serializeInt(buffer, arg),
            u32 => serializeUint(buffer, arg),
            else => @compileError("Unexpected int type."),
        },
        .@"struct" => switch (T) {
            Fixed => serializeFixed(buffer, arg),
            GenericNewId => serializeGenericNewId(buffer, arg),
            else => serializeUint(buffer, @bitCast(arg)),
        },
        .@"enum" => |e| switch (e.tag_type) {
            i32 => serializeInt(buffer, @intFromEnum(arg)),
            u32 => serializeUint(buffer, @intFromEnum(arg)),
            else => @compileError("Unexpected enum tag type."),
        },
        .pointer => switch (T) {
            []const u8 => serializeArray(buffer, arg),
            [:0]const u8 => serializeString(buffer, arg),
            else => @compileError("Unexpected pointer type."),
        },
        .optional => |o| switch (o.child) {
            [:0]const u8 => serializeOptionalString(buffer, arg),
            else => serializeUint(buffer, if (arg) |obj| obj.getId() else 0),
        },
        else => @compileError(std.fmt.comptimePrint("Unexpected arg type: {s}", .{@typeName(T)})),
    };
}

/// Writes `int` to the beginning of `buffer` and returns `@sizeOf(i32)`.
fn serializeInt(buffer: []u8, int: i32) usize {
    std.mem.bytesAsValue(i32, buffer[0..@sizeOf(i32)]).* = int;
    return @sizeOf(i32);
}

test "serialize int" {
    var buf: [4]u8 = undefined;
    try std.testing.expectEqual(4, serializeInt(&buf, -65536));
    try std.testing.expectEqual(-65536, std.mem.bytesToValue(i32, &buf));
}

/// Writes `uint` to the beginning of `buffer` and returns `@sizeOf(u32)`.
fn serializeUint(buffer: []u8, uint: u32) usize {
    std.mem.bytesAsValue(u32, buffer[0..@sizeOf(u32)]).* = uint;
    return @sizeOf(u32);
}

test "serialize uint" {
    var buf: [4]u8 = undefined;
    try std.testing.expectEqual(4, serializeUint(&buf, 65536));
    try std.testing.expectEqual(65536, std.mem.bytesToValue(u32, &buf));
}

/// Serializes a nullable object as its id, or zero if null. Returns @sizeOf(u32).
fn serializeOptionalObject(buffer: []u8, object: anytype) usize {
    return serializeUint(buffer, if (object) |o| o.getId() else 0);
}

test "serialize optional object" {
    const obj1: ?TestInterface = @enumFromInt(3);
    const obj2: ?TestInterface = null;

    var buf: [4]u8 = undefined;
    try std.testing.expectEqual(4, serializeOptionalObject(&buf, obj1));
    try std.testing.expectEqual(3, std.mem.bytesToValue(u32, &buf));
    try std.testing.expectEqual(4, serializeOptionalObject(&buf, obj2));
    try std.testing.expectEqual(TestInterface.invalid, std.mem.bytesToValue(TestInterface, &buf));
}

/// Writes the backing i32 of `fixed` to the beginning of `buffer` and returns `@sizeOf(i32)`.
fn serializeFixed(buffer: []u8, fixed: Fixed) usize {
    return serializeInt(buffer, @intFromEnum(fixed));
}

test "serialize fixed" {
    var buf: [4]u8 = undefined;
    try std.testing.expectEqual(4, serializeFixed(&buf, .from(2.1)));
    try std.testing.expectApproxEqAbs(2.1, std.mem.bytesToValue(Fixed, &buf).to(f64), 0.01);
}

/// Writes the length of `string` including the null terminator followed by the contents of `string`
/// to the beginning of the buffer.
/// Returns @sizeOf(u32) plus the serialized length rounded up to
/// the nearest multiple of 4 bytes.
/// For a string of length 12, returns 4 + roundup4(12 + 1) --> 4 + roundup4(13) --> 4 + 16 --> 20.
fn serializeString(buffer: []u8, string: [:0]const u8) usize {
    const written = serializeUint(buffer, @intCast(string.len + 1));
    @memcpy(buffer[written..][0..string.len], string);
    buffer[written + string.len] = 0;
    return written + roundup4(string.len + 1);
}

test "serialize string" {
    const message = "hello, world!";
    var buf: [20]u8 = undefined;
    try std.testing.expectEqual(buf.len, serializeString(&buf, message));
    const len = std.mem.bytesToValue(u32, buf[0..4]);
    try std.testing.expectEqual(message.len + 1, len);
    try std.testing.expectEqualSlices(u8, message, buf[4..][0..message.len]);
}

/// Same as `serializeString`, except if `string` is null,
/// a zero is written to signify no content and @sizeOf(u32) is returned.
fn serializeOptionalString(buffer: []u8, string: ?[:0]const u8) usize {
    return if (string) |s|
        serializeString(buffer, s)
    else
        serializeUint(buffer, 0);
}

test "serialize optional string" {
    const message = "hello, world!";
    var buf: [20]u8 = undefined;
    try std.testing.expectEqual(buf.len, serializeOptionalString(&buf, message));
    const len = std.mem.bytesToValue(u32, buf[0..4]);
    try std.testing.expectEqual(message.len + 1, len);
    try std.testing.expectEqualSlices(u8, message, buf[4..][0..message.len]);

    try std.testing.expectEqual(4, serializeOptionalString(&buf, null));
    const len2 = std.mem.bytesToValue(u32, buf[0..4]);
    try std.testing.expectEqual(0, len2);
}

/// Writes the interface of `new_id` as a nonnull string, followed by version as a uint,
/// followed by the id itself, also as a u32.
/// Returns the serialized length of interface plus `2 * @sizeOf(u32)`.
fn serializeGenericNewId(buffer: []u8, new_id: GenericNewId) usize {
    var written = serializeString(buffer, new_id.interface);
    written += serializeUint(buffer[written..], new_id.version);
    return written + serializeUint(buffer[written..], new_id.new_id);
}

test "serialize generic new id" {
    const new_id: GenericNewId = .init(TestInterface, .v2, 1);
    var buf: [28]u8 = undefined;
    try std.testing.expectEqual(buf.len, serializeGenericNewId(&buf, new_id));

    const len = std.mem.bytesToValue(u32, buf[0..4]);
    try std.testing.expectEqual(TestInterface.interface.len + 1, len);
    const serialized_interface = buf[4..][0..TestInterface.interface.len];
    try std.testing.expectEqualSlices(u8, TestInterface.interface, serialized_interface);
    try std.testing.expectEqual(2, std.mem.bytesToValue(u32, buf[20..24]));
    try std.testing.expectEqual(1, std.mem.bytesToValue(u32, buf[24..28]));
}

/// Writes the length of `array` followed by the bytes of `array` to the beginning of the buffer.
/// Returns @sizeOf(u32) plus the serialized length rounded up to the nearest multiple of 4 bytes.
/// For an array of length 12, returns 4 + roundup4(12) --> 4 + roundup4(12) --> 4 + 12 --> 16.
fn serializeArray(buffer: []u8, array: []const u8) usize {
    const written = serializeUint(buffer, @intCast(array.len));
    @memcpy(buffer[written..][0..array.len], array);
    return written + roundup4(array.len);
}

test "serialize array" {
    const arr = [_]u8{ 0, 1, 2, 3, 4, 5, 6 };
    var buf: [12]u8 = undefined;
    try std.testing.expectEqual(buf.len, serializeArray(&buf, &arr));
    const len = std.mem.bytesToValue(u32, buf[0..4]);
    try std.testing.expectEqual(arr.len, len);
    try std.testing.expectEqualSlices(u8, &arr, buf[4..][0..arr.len]);
}

/// Returns the sum of the serialized lengths of all fields of `args`, plus @sizeOf(Header).
fn calculateArgsLength(args: anytype) u16 {
    var length: u16 = @intCast(@sizeOf(Header));
    inline for (@typeInfo(@TypeOf(args)).@"struct".fields) |field| {
        const f = @field(args, field.name);
        length += switch (field.type) {
            []const u8 => @intCast(roundup4(f.len) + 4),
            [:0]const u8 => @intCast(roundup4(f.len + 1) + 4),
            ?[:0]const u8 => if (f) |s| @intCast(roundup4(s.len + 1) + 4) else 4,
            GenericNewId => @intCast(roundup4(f.interface.len + 1) + 12),
            else => 4,
        };
    }
    return length;
}

test "calculate args length" {
    // Start with 8 bytes for header
    const args = .{
        @as(i32, -1), // + 4 = 12
        @as(u32, 2), // + 4 = 16
        Fixed.from(12.34), // + 4 = 20
        @as(?[:0]const u8, null), // + 4 = 24
        @as([]const u8, &.{ 0, 1, 2, 3, 4 }), // + 4 + 8 = 36
    };

    try std.testing.expectEqual(36, calculateArgsLength(args));
}

/// Deserialize a single field of type `T` from `data`
/// Returns the element, `T`, and the bytes consumed
fn deserializeField(comptime T: type, data: []const u8) DeserializeError!struct { T, usize } {
    return switch (@typeInfo(T)) {
        .int => switch (T) {
            i32 => deserializeInt(data),
            u32 => deserializeUint(data),
            else => @compileError("Unexpected int type."),
        },
        .@"struct" => switch (T) {
            GenericNewId => deserializeGenericNewId(data),
            Fixed => deserializeFixed(data),
            else => deserializeBitfield(T, data),
        },
        .pointer => switch (T) {
            []const u8 => deserializeArray(data),
            [:0]const u8 => deserializeString(data),
            else => @compileError("Invalid pointer type in incoming message."),
        },
        .optional => |o| switch (o.child) {
            [:0]const u8 => deserializeOptionalString(data),
            else => deserializeOptionalObject(o.child, data),
        },
        .@"enum" => deserializeEnum(T, data),
        else => @compileError(std.fmt.comptimePrint("Unexpected arg type: {s}", .{@typeName(T)})),
    };
}

fn deserializeInt(data: []const u8) DeserializeError!struct { i32, usize } {
    if (data.len < 4) return error.InvalidArguments;
    return .{ std.mem.bytesToValue(i32, data[0..4]), 4 };
}

test "deserialize int" {
    const int: i32 = -1;
    try std.testing.expectEqual(.{ int, @sizeOf(i32) }, try deserializeInt(std.mem.asBytes(&int)));
    try std.testing.expectError(error.InvalidArguments, deserializeInt(&.{ 0, 1, 2 }));
}

fn deserializeUint(data: []const u8) DeserializeError!struct { u32, usize } {
    if (data.len < 4) return error.InvalidArguments;
    return .{ std.mem.bytesToValue(u32, data[0..4]), 4 };
}

test "deserialize uint" {
    const uint: u32 = 1024;
    try std.testing.expectEqual(.{ uint, @sizeOf(u32) }, try deserializeUint(&.{ 0, 4, 0, 0 }));
    try std.testing.expectError(error.InvalidArguments, deserializeUint(&.{ 0, 1, 2 }));
}

fn deserializeFixed(data: []const u8) DeserializeError!struct { Fixed, usize } {
    if (data.len < 4) return error.InvalidArguments;
    const raw, _ = try deserializeInt(data);
    return .{ @enumFromInt(raw), 4 };
}

test "deserialize fixed" {
    const fixed: Fixed = .from(1.23);
    const res, const len = try deserializeFixed(std.mem.asBytes(&fixed));
    try std.testing.expectApproxEqAbs(1.23, res.to(f64), 0.01);
    try std.testing.expectEqual(len, 4);
    try std.testing.expectError(error.InvalidArguments, deserializeFixed(&.{ 0, 1, 2 }));
}

fn deserializeArray(data: []const u8) DeserializeError!struct { []const u8, usize } {
    if (data.len < 4) return error.InvalidArguments;
    const len, _ = try deserializeUint(data);
    if (roundup4(len) > data.len - 4) return error.InvalidArguments;
    return .{ data[4..][0..len], 4 + roundup4(len) };
}

test "deserialize array" {
    const data = [_]u8{ 8, 0, 0, 0, 0, 1, 2, 3, 4, 5, 6, 7 };
    const arr, const len = try deserializeArray(&data);
    try std.testing.expectEqual(data.len, len);
    try std.testing.expectEqualSlices(u8, data[4..], arr);
    try std.testing.expectError(error.InvalidArguments, deserializeArray(data[0..10]));
}

fn deserializeString(data: []const u8) DeserializeError!struct { [:0]const u8, usize } {
    if (data.len < 4) return error.InvalidArguments;
    const len, _ = try deserializeUint(data);
    if (len == 0 or roundup4(len) > data.len - 4) return error.InvalidArguments;
    return .{ @ptrCast(data[4..][0 .. len - 1]), 4 + roundup4(len) };
}

test "deserialize string" {
    const string = "hello, world!";
    const data = [_]u8{ 14, 0, 0, 0 } ++ string ++ [_]u8{ 0, 8, 9, 1, 2, 3, 4 };
    const str, const len = try deserializeString(data);
    try std.testing.expectEqual(4 + roundup4(string.len), len);
    try std.testing.expectEqualSlices(u8, data[4..][0..string.len], str);
    try std.testing.expectError(error.InvalidArguments, deserializeString(data[0..10]));
    try std.testing.expectError(error.InvalidArguments, deserializeString(&.{ 0, 0, 0, 0 }));
}

fn deserializeOptionalString(data: []const u8) DeserializeError!struct { ?[:0]const u8, usize } {
    if (data.len < 4) return error.InvalidArguments;
    const len, _ = try deserializeUint(data);
    if (len == 0) return .{ null, 4 };
    if (roundup4(len) > data.len - 4) return error.InvalidArguments;

    return .{ @ptrCast(data[4..][0 .. len - 1]), 4 + roundup4(len) };
}

test "deserialize optional string" {
    const string = "hello, world!";
    const data = [_]u8{ 14, 0, 0, 0 } ++ string ++ [_]u8{ 0, 8, 9, 1, 2, 3, 4 };
    const str, const len = try deserializeOptionalString(data);
    try std.testing.expectEqual(4 + roundup4(string.len), len);
    try std.testing.expect(str != null);
    try std.testing.expectEqualSlices(u8, data[4..][0..string.len], str.?);
    try std.testing.expectError(error.InvalidArguments, deserializeOptionalString(data[0..10]));
    const str2, const len2 = try deserializeOptionalString(&.{ 0, 0, 0, 0 });
    try std.testing.expectEqual(4, len2);
    try std.testing.expectEqual(null, str2);
}

fn deserializeGenericNewId(data: []const u8) DeserializeError!struct { GenericNewId, usize } {
    if (data.len < 4) return error.InvalidArguments;
    const interface, const len = try deserializeString(data);
    if (len + 8 > data.len) return error.InvalidArguments;
    const version, _ = try deserializeUint(data[len..]);
    const new_id, _ = try deserializeUint(data[len..][4..]);

    if (version == 0 or new_id == 0) return error.InvalidArguments;

    return .{ .{
        .interface = interface,
        .version = version,
        .new_id = new_id,
    }, len + 8 };
}

test "deserialize generic new id" {
    const new_id: GenericNewId = .init(TestInterface, .v2, 1);
    var buf: [128]u8 = undefined;
    const len = serializeGenericNewId(&buf, new_id);
    const new_id2, const len2 = try deserializeGenericNewId(&buf);

    try std.testing.expectEqual(len, len2);
    try std.testing.expectEqual(new_id.version, new_id2.version);
    try std.testing.expectEqual(new_id.new_id, new_id2.new_id);
    try std.testing.expectEqualSlices(u8, new_id.interface, new_id2.interface);

    const new_id3: GenericNewId = .init(TestInterface, .v1, 0);
    _ = serializeGenericNewId(&buf, new_id3);
    try std.testing.expectError(error.InvalidArguments, deserializeGenericNewId(&buf));
}

fn deserializeBitfield(comptime T: type, data: []const u8) DeserializeError!struct { T, usize } {
    if (data.len < 4) return error.InvalidArguments;
    const val, const len = try deserializeUint(data);
    return .{ @bitCast(val), len };
}

test "deserialize bitfield" {
    const bf: TestBitfield = .{ .one = false, .two = true };
    const res, const len = try deserializeBitfield(TestBitfield, &.{ 2, 0, 0, 0 });
    try std.testing.expectEqual(4, len);
    try std.testing.expectEqual(bf, res);
    try std.testing.expectError(error.InvalidArguments, deserializeBitfield(TestBitfield, &.{0}));
}

fn deserializeEnum(comptime T: type, data: []const u8) DeserializeError!struct { T, usize } {
    if (data.len < 4) return error.InvalidArguments;
    const val, const len = switch (@typeInfo(T).@"enum".tag_type) {
        i32 => try deserializeInt(data),
        u32 => try deserializeUint(data),
        else => @compileError("Unexpected enum tag type."),
    };
    const enum_val = std.enums.fromInt(T, val) orelse return error.InvalidArguments;
    return .{ enum_val, len };
}

test "deserialize enum" {
    const res, const len = try deserializeEnum(TestEnum, &.{ 0, 0, 0, 0 });
    try std.testing.expectEqual(4, len);
    try std.testing.expectEqual(TestEnum.zero, res);
    const res2, _ = try deserializeEnum(TestEnum, &.{ 1, 0, 0, 0 });
    try std.testing.expectEqual(TestEnum.one, res2);
    try std.testing.expectError(error.InvalidArguments, deserializeEnum(TestEnum, &.{ 2, 0, 0, 0 }));
}

fn deserializeOptionalObject(
    comptime T: type,
    data: []const u8,
) DeserializeError!struct { ?T, usize } {
    if (data.len < 4) return error.InvalidArguments;
    const obj, const len = try deserializeEnum(T, data);
    if (obj == .invalid) return .{ null, len };
    return .{ obj, len };
}

test "deserialize optional object" {
    const t: ?TestInterface = @enumFromInt(2);
    const t2: ?TestInterface = null;
    const res, const len = try deserializeOptionalObject(TestInterface, &.{ 2, 0, 0, 0 });
    try std.testing.expectEqual(4, len);
    try std.testing.expectEqual(t, res);
    const res2, _ = try deserializeOptionalObject(TestInterface, &.{ 0, 0, 0, 0 });
    try std.testing.expectEqual(t2, res2);
}

fn roundup4(value: anytype) @TypeOf(value) {
    const T = @TypeOf(value);
    return switch (@typeInfo(T)) {
        .int => (value + 3) & ~@as(T, 3),
        else => @compileError("Unsupported type (roundup4)."),
    };
}

test "roundup4" {
    try std.testing.expectEqual(0, roundup4(@as(usize, 0)));
    try std.testing.expectEqual(4, roundup4(@as(usize, 4)));
    try std.testing.expectEqual(4, roundup4(@as(usize, 3)));
    try std.testing.expectEqual(24, roundup4(@as(u18, 21)));
    try std.testing.expectEqual(100, roundup4(@as(u16, 97)));
    try std.testing.expectEqual(1024, roundup4(@as(u32, 1021)));
    try std.testing.expectEqual(1024, roundup4(@as(u32, 1022)));
    try std.testing.expectEqual(1024, roundup4(@as(u32, 1023)));
    try std.testing.expectEqual(1024, roundup4(@as(u32, 1024)));
}

/// Fake interface to use in serialization and deserialization unit tests.
/// Mirrors what is generated by the scanner.
const TestInterface = enum(u32) {
    invalid = 0,
    _,
    const interface = "hello, world!";
    const Version = enum(u32) {
        v1 = 1,
        v2 = 2,
    };

    fn getId(self: TestInterface) u32 {
        return @intFromEnum(self);
    }
};

/// Fake enum to use in serialization and deserialization unit tests.
/// Mirrors what is generated by the scanner.
const TestEnum = enum(i32) {
    zero = 0,
    one = 1,
};

/// Fake bitfield to use in serialization and deserialization unit tests.
/// Mirrors what is generated by the scanner
const TestBitfield = packed struct(u32) {
    one: bool = false,
    two: bool = false,
    _: u30 = 0,
};
